name: 'Android Release Debug'

on:
  push:
    branches:
      - master # Or your testing branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build-android-debug:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install specific NDK version (Trying NDK 26)
        # Let's try a slightly newer NDK version, just in case
        run: sdkmanager "ndk;26.1.10909125"

      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Install frontend dependencies
        run: npm ci

      - name: Extract app version
        id: app_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Decode Android keystore
        id: decode_keystore
        run: |
          echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" | base64 --decode > android-release.jks
          echo "keystore_path=$(pwd)/android-release.jks" >> $GITHUB_OUTPUT
        shell: bash

      - name: DEBUG - Check package.json script and run tauri info
        run: |
          echo "--- package.json scripts ---"
          node -p "require('./package.json').scripts" || echo "Could not read package.json scripts"
          echo "--- npx tauri info ---"
          # Run tauri info to check environment detection
          npx tauri info
          echo "--- Running build command directly with max verbosity ---"

      - name: Build Signed Android App (APK and AAB) - MAX VERBOSITY
        # Use npx for direct execution, add -vvv for max tauri verbosity
        # Add RUST_LOG=debug for verbose Rust/Cargo output
        run: npm run tauri android build
        env:
          # Ensure NDK_HOME matches the installed NDK version
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125 # Updated to NDK 26 path
          TAURI_ANDROID_KEYSTORE_PATH: ${{ steps.decode_keystore.outputs.keystore_path }}
          TAURI_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_PASSWORD }}
          TAURI_ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_RELEASE_KEY }}
          TAURI_ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          CI: true
          # Add Rust debug logging
          RUST_LOG: debug
          # Potentially force specific tool versions if needed (usually not required)
          # GRADLE_HOME: ...
          # JAVA_HOME: ... (already set by setup-java)

      - name: DEBUG - List build artifacts directory
        # Run this regardless of previous step outcome to see if anything was created
        if: always()
        run: |
          echo "--- Listing src-tauri/target/release (if exists) ---"
          ls -lR src-tauri/target/release || echo "src-tauri/target/release not found or empty"
          echo "--- Finding apk/aab files in src-tauri ---"
          find src-tauri -name "*.apk" -o -name "*.aab" || echo "No apk or aab files found in src-tauri"
          echo "--- Finding apk/aab files everywhere ---"
          find . -name "*.apk" -o -name "*.aab" || echo "No apk or aab files found anywhere"


      # --- Renaming and Release Steps ---
      # Removing continue-on-error for clearer debugging for now.
      # These steps will likely fail if the build step continues to fail silently.
      - name: Rename APK artifact
        run: |
          # Add ls before mv to see if the file exists just before trying to move it
          ls -l src-tauri/target/release/android-artifacts/app-universal-release-signed.apk
          mv src-tauri/target/release/android-artifacts/app-universal-release-signed.apk tsuuchinoko-v${{ steps.app_version.outputs.version }}-universal.apk

      - name: Rename AAB artifact
        run: |
           # Add ls before mv
           ls -l src-tauri/target/release/android-artifacts/app-universal-release.aab
           mv src-tauri/target/release/android-artifacts/app-universal-release.aab tsuuchinoko-v${{ steps.app_version.outputs.version }}-universal.aab

      - name: Create GitHub Release
        # Only run if build and rename likely succeeded
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.app_version.outputs.version }}
          name: Tsuuchinoko v${{ steps.app_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            tsuuchinoko-v${{ steps.app_version.outputs.version }}-universal.apk
            tsuuchinoko-v${{ steps.app_version.outputs.version }}-universal.aab
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}